wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.22.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_perplexity
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.8.5
    start_time: 1664228863
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      2:
      - 1
      - 2
      - 3
      - 5
      - 9
      - 11
      3:
      - 7
      - 13
      4: 3.8.5
      5: 0.12.9
      6: 4.22.0
      8:
      - 3
      - 5
